spring:
  application:
    name: moneymaker
  datasource:
    url: jdbc:postgresql://localhost:5432/moneymaker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
